name: Deploy Documentation on Release

on:
  workflow_dispatch:

jobs:
  docs:
    uses: scikit-package/release-scripts/.github/workflows/_release-docs.yml@v0
    with:
      project: diffpy.morph
      python_version: 3.13
      c_extension: false
      headless: false
